### ISSUE TITLE
Links with target=_blank ignores default browser?

### ISSUE THREAD

**Issue by connorjburton** [ChangemakerStudios/Papercut#105]
It seems if you have a link without target _blank it will open the link in your default browser

If you have a link with target _blank it will open the link in IE

Could you confirm this? Thanks

**Comment by jimbobmcgee** [comment]
This may be a subtlety of the WebBrowser control used to render HTML content.  The WebBrowser uses IE internally, so it stands to reason that telling it to open a new window (i.e. `target="_blank"`) would open a new IE window.

Since Papercut already handles (and cancels) the WebBrowser control's Navigating event, so it can call `Process.Start(theUrl)` to open your default browser, I suspect that the IE's decision to make the new window happens *before* the decision to navigate, so that cancellation never happens.

In the old .NET Forms WebBrowser, there was a NewWindow event that could be coerced to cancel opening a new window (`browser.NewWindow += (s, e) => { e.Cancel = true; };`).  However, it looks like that event never made it into the WPF version of the control.

Instead, an example in the MSDN documentation suggests that you can get a reference to the underlying IE COM object and hook `NewWindow2` to the same effect.  It looks like Papercut does something fairly similar to prevent showing script errors.

https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.webbrowser?view=netframework-4.7.2

**Comment by Jaben** [comment]
I'll investigate a bit more
