### ISSUE TITLE
Can not start HTTP server at port 37408. Exception: One or more errors occurred.

### ISSUE THREAD

**Issue by MayWorkman** [ChangemakerStudios/Papercut#117]
I am running a local Wordpress site using Docker on a Windows 10 machine. I would like to be able to use Papercut with it but it is not working. Using the WP Mail SMTP plugin but an older version than what you see in wordpress.org. Using Papercut v5.1.23

I installed PaperCut from github
When I start it this is what the logs say:
25-Jun-18 5:20:04 PM [Information] Server Ready - Listening for New Connections "127.0.0.1":25 
25-Jun-18 5:20:04 PM [Information] Starting Server Smtp 
25-Jun-18 5:20:04 PM [Information] Server Ready - Listening for New Connections "127.0.0.1":37402 
25-Jun-18 5:20:04 PM [Information] Starting Server Papercut 
25-Jun-18 5:20:03 PM [Information] Attempting to Load Rules from "C:\Program Files (x86)\Changemaker Studios\Papercut\rules.json" on AppReady 
25-Jun-18 5:20:03 PM **[Error] Can not start HTTP server at port 37408. Exception: One or more errors occurred.**
25-Jun-18 5:20:03 PM [Information] Running Plug-In "Papercut Seq Logging" "1.0.0.0" "Papercut Serilog to Seq (http://getseq.net) local instance" 
25-Jun-18 5:20:03 PM [Information] Running Plug-In "Verbose (JSON) Serilog Logging" "5.1.23.0" "Verbose (JSON) Serilog Logging Support for Papercut" 
25-Jun-18 5:20:03 PM [Information] Running Plug-In "WebUI" "1.0.0" "Provides a web UI to manage the email messages for Papercut." 
25-Jun-18 5:20:02 PM [Information] Default Message Save Path is Set to "C:\Users\MayWorkman\AppData\Roaming\Papercut" 
25-Jun-18 5:20:02 PM [Information] Loading Messages from the Following Path(s) ["C:\Users\MayWorkman\AppData\Roaming\Papercut", "C:\Program Files (x86)\Changemaker Studios\Papercut\", "C:\Program Files (x86)\Changemaker Studios\Papercut\Incoming"]

Even though this doesn't matter right now - my settings in WP are: 
Override default SMTP settings: checked
SMTP Host: 127.0.0.1
SMTP Port: 25
No encryption
No: Do not use SMTP authentication.

**Comment by Jaben** [comment]
The Papercut Web UI cannot run because a process is already using port 37408 on your machine. 

Run netstat on the command line to see what specifically is using that port (37408):

```netstat -a -o```

Should display something like:

![image](https://user-images.githubusercontent.com/448726/42612121-7a2dd70e-8567-11e8-994b-3990523f58a4.png)

Then, if you look in Task Manager and find the Process ID, it should tell you what's already using that port:

![image](https://user-images.githubusercontent.com/448726/42612161-c596c728-8567-11e8-9ce3-ce3b8e8b4a50.png)

**Comment by ScottShingler** [comment]
I'm running Papercut 5.1.70.0. I've noticed that the Papercut SMTP Service uses that port (37408). This service is set to start automatically. However, when I try to launch the papercut UI while the service is running, the UI does not appear, though I can see the Papercut process running in Task Manager.

If I kill the Papercut process and stop the Papercut SMTP Service, I can then start the Papercut UI normally, but get the error reported by @MayWorkman :
 
    [Error] Can not start HTTP server at port 37408. Exception: One or more errors occurred.

I have verified that no process is using port 37408 at the time (using Sysinternals TCPView).

@MayWorkman Since you're trying to communicate with Papercut on your Windows host from a Docker container, try configuring WordPress SMTP Host to use `host.docker.internal` instead of `127.0.0.1`.

**Comment by jijiechen** [comment]
Thanks for reporting. I'll try to reproduce it.

**Comment by itimgit** [comment]
When opening PaperCut as Administrator, error goes away (for me)

**Comment by ScottShingler** [comment]
Just tried opening PaperCut as Administrator. It still does not display the UI or the systray icon if the Papercut SMTP Service is running. However, if the Papercut SMTP Service is stopped and I launch Papercut as an Administrator, the error goes away as @itimgit mentioned.

**Comment by jzabroski** [comment]
Can we add a list of KnownIssues.MD and include this?

**Comment by MayWorkman** [comment]
Was able to finally get back to this problem.

Port 37408 is being used 
![image](https://user-images.githubusercontent.com/2749638/46669845-dc08cb00-cbd0-11e8-9f9c-39a4d9a595d1.png)

by System
![image](https://user-images.githubusercontent.com/2749638/46669913-0e1a2d00-cbd1-11e8-94c1-05bf306b89ea.png)

I tried what @ScottShingler said "configuring WordPress SMTP Host to use `host.docker.internal` instead of `127.0.0.1`". And that worked. The port 37408 error is still there but that was not what was causing me problems.

**Comment by wavedrop** [comment]
> When opening PaperCut as Administrator, error goes away (for me)

Just wanted to add that this worked for me as well given the following error:

[Error] Can not start HTTP server at port 37408.

Thank you.
