### ISSUE TITLE
Exe issues

### ISSUE THREAD

**Issue by salarmehr** [ChangemakerStudios/Papercut#142]
![image](https://user-images.githubusercontent.com/2582036/54500009-7c2b0300-496c-11e9-976c-74c93074133e.png)
 I got above screen, why the publisher is unknown? 

![image](https://user-images.githubusercontent.com/2582036/54500067-efcd1000-496c-11e9-902b-6b1d075ee986.png)

![image](https://user-images.githubusercontent.com/2582036/54500074-06736700-496d-11e9-891b-fd59d8371a5e.png)

**Comment by salarmehr** [comment]
I cannot run the app because of the above security issues on the Win 10.

**Comment by Jaben** [comment]
These are two different issues. The publisher isn't known because this is an open source community project and it costs money to buy a code certificate every year. You can just click the button "run anyway" -- or send me $75 to buy a code certificate.

Second issue is a false positive from your anti-virus software. You can add an exception.

Or you can download the source and built the app yourself -- then you can be sure.

**Comment by salarmehr** [comment]
I believe this is an issue that needs to be addressed anyway and there should ways to make it clear and safe to the world. M antivirus allows other apps to be installed without any issue. e.g. https://hostsfileeditor.com/.  I'm sure this issue is fixable. Could you consider opening the ticket and resolve it?

Thanks for crating this awesome tool.
