### ISSUE TITLE
Delete all button

### ISSUE THREAD

**Issue by hugobyrne** [ChangemakerStudios/Papercut#143]
Just want to add my vote for a single-click "Delete All" emails button.
I know this has been raised previously.
Thanks for making a great program.

**Comment by Jaben** [comment]
CTRL+A
"DELETE" key or Delete Button.

You can also do a range by selecting, holding shift and selecting the group of items to delete. Press "DELETE" key or Delete button.

**Comment by edvdave** [comment]
Dear Jaben,

first of all thank you for this brilliant application. 
A Delete-All button would be highly appreciated, because Papercut can not handle a removal with CTRL-A of 5000+ Mails. (often application freezes, hangs and depends on pc hardware ressources)
I do use Papercut as local Mail Gateway and Mail Gather Station for Serverlogs and forward them.

Is it possible to shedule a removal of the inbox ?

best regards

lukas

**Comment by Jaben** [comment]
I'll add a rule to clean out old mail.

**Comment by edvdave** [comment]
> 
> 
> I'll add a rule to clean out old mail.

Thank you. :)

**Comment by Jaben** [comment]
Added a button in latest -- "clean out old mail" rule will need to be another issue.
