### ISSUE TITLE
Embedded IE crashes Papercut

### ISSUE THREAD

**Issue by michaelblyons** [ChangemakerStudios/Papercut#43]
I had to add `about:internet` to my Trusted Sites in IE's security options to prevent the application from crashing immediately.

I don't know if this is an "issue" per se, but I wanted it to be linked to the project for anyone else who ran into the same problem.

**Comment by jimbobmcgee** [comment]
I see the same if I run Papercut with IE Enhanced Security enabled (which it is by default on Windows Server).

@Jaben...
I think this *might* be fixable (or at least recoverable) by adding a `try`/`catch` around the call to `htmlView.Source` in the `MessageDetailHtmlViewModel.OnViewLoaded` method  (approx line 144):

```
this.GetPropertyValues(p => p.HtmlFile)
    .Subscribe(file =>
    {
        try { typedView.htmlView.Source = new Uri(string.IsNullOrWhiteSpace(file) ? "about:blank" : file); }
        catch { /* Do something here to inform user of Trusted Sites requirement */ }
    });
```

You might also be able to change which address requires trusting by altering your MarkOfTheWeb string in the UIStrings.resx file.  I haven't tried this explicitly, but the following might limit the trust scope, instead of requiring `about:internet` (which 'feels' too expansive for a 'trusted' zone):

```
<!-- saved from url=(0014)about:papercut_exe -->
```

Alternatively, setting it to the localhost string might coerce it to Local Intranet, instead of Trusted Sites, which might relax the requirement (although might be more dangerous, strictly speaking):

```
<!-- saved from url=(0016)http://localhost -->
```

Hope this helps...

**Comment by Jaben** [comment]
@jimbobmcgee Thanks for this research. I've been at a bit of a loss as to the best path for a fix for this issue. I'll look into integrating these suggestions in the next release.

**Comment by jimbobmcgee** [comment]
@Jaben - You're welcome.

I don't know if it is the *best* path, per se; I was never able to make the WebBrowser control crash in a quick sample app, even if I used a MOTW to define a 'zone' that wasn't trusted, regardless of whether I had a `try`/`catch` around setting the `WebBrowser.Source`, so my first suggestion of adding `try`/`catch` to the `OnViewLoaded` method might be a red-herring.

The second idea is really more around *limiting* the scope of the trust that has to be added to work around the functional issue.  Adding `about:internet` to Trusted Sites has wider-reaching issues, that may serve to negate the security boundary that Trusted Sites is supposed to provide.  It is *probably* better that mail content read by Papercut *isn't* trusted by default, just in case someone might be relaying real internet mail through it (although that assumes a use-case outside of Papercut's intent).

I can't build Papercut at the moment because of dependency issues on my dev machine, but if you can hook `AppDomain.CurrentDomain.UnhandledException` or `AppDomain.CurrentDomain.FirstChanceException` to log the full exception, inner exception chain and stack trace, in an interim/debug build, that might give us a better chance of finding the real bug.

In the meantime, a dedicated scope for trust (e.g. the `about:papercut` MOTW) and a documentation note regarding trusting that scope on servers with IE Enhanced Security mode enabled will probably suffice.
