### ISSUE TITLE
Chocolatey Install for Papercut.Service

### ISSUE THREAD

**Issue by Jaben** [ChangemakerStudios/Papercut#66]
Added Choco install for the service

**Comment by jijiechen** [comment]
Good plan, I like it.

**Comment by jijiechen** [comment]
Please keep it open

Sent from my iPhone

On Feb 7, 2019, at 07:21, stale[bot] <notifications@github.com<mailto:notifications@github.com>> wrote:


Aloha! I'm ScissorBot ✂️ -- the bot in charge of keeping the issues tidy. It looks like this issue is stale due to lack of activity. Unfortunately, I'll be closing it if there is no further activity. 😞 Please contribute to the issue to keep it open. Thanks!

**Comment by Marcus-James-Adams** [comment]
please dont close this, this would be  a brillent move
